import { useState, useEffect } from 'react'
import { useLocation } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  Settings, 
  RotateCcw, 
  X, 
  ChevronLeft, 
  ChevronRight,
  Utensils,
  Coffee,
  Sun,
  Moon,
  Apple,
  Loader2,
  Plus,
  Trash2
} from 'lucide-react'
import Navbar from '../../components/Navbar'
import mealPlannerService from '../../services/mealPlannerService'
import { useAuth } from '../../hooks/useAuth'
import { useToast } from '../../components/ToastContainer'
import LoadingSpinner from '../../components/LoadingSpinner'

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
const MEAL_TYPES = [
  { key: 'breakfast', label: 'Breakfast', icon: Coffee },
  { key: 'lunch', label: 'Lunch', icon: Sun },
  { key: 'dinner', label: 'Dinner', icon: Moon },
  { key: 'snack', label: 'Snack', icon: Apple }
]

const SWAP_REASONS = [
  "Don't like ingredients",
  "Too hard to cook",
  "Just want change"
]

const MealPlanner = () => {
  const location = useLocation()
  const { isGuest } = useAuth()
  const { showToast } = useToast()
  
  // Check if we should start wizard immediately (before state initialization)
  const shouldStartWizard = location.state?.startWizard === true && !isGuest
  
  const [weeklyPlan, setWeeklyPlan] = useState(null)
  const [activeDayIndex, setActiveDayIndex] = useState(0)
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(shouldStartWizard) // Start generating immediately if startWizard
  const [preferencesOpen, setPreferencesOpen] = useState(false)
  const [excludedFoods, setExcludedFoods] = useState([])
  const [newFoodInput, setNewFoodInput] = useState('')
  const [swapModalOpen, setSwapModalOpen] = useState(false)
  const [selectedMeal, setSelectedMeal] = useState(null)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  // Get current day index on mount
  useEffect(() => {
    const today = new Date().getDay()
    // Convert Sunday (0) to 6, Monday (1) to 0, etc.
    const dayIndex = today === 0 ? 6 : today - 1
    setActiveDayIndex(dayIndex)
  }, [])

  // Load existing plan if coming from swap button or auto-generate if coming from dashboard
  useEffect(() => {
    const startWizard = location.state?.startWizard === true
    const loadPlan = location.state?.loadPlan === true
    
    // Load existing plan from swap button
    if (loadPlan && !weeklyPlan && !isGuest && !hasAutoGenerated) {
      console.log('[MealPlanner] Loading existing plan from swap navigation')
      setHasAutoGenerated(true)
      // Clear the state to prevent re-triggering
      window.history.replaceState({}, document.title)
      
      const loadExistingPlan = async () => {
        if (isGuest) {
          showToast('Please register to view meal plans', 'error')
          return
        }

        try {
          setLoading(true)
          const plan = await mealPlannerService.getWeeklyPlan()
          if (plan) {
            setWeeklyPlan(plan)
            console.log('[MealPlanner] Existing plan loaded successfully')
          } else {
            showToast('No meal plan found. Please generate one first.', 'info')
          }
        } catch (error) {
          console.error('Error loading meal plan:', error)
          showToast(
            error.response?.data?.detail || 'Failed to load meal plan. Please try again.',
            'error'
          )
        } finally {
          setLoading(false)
        }
      }
      loadExistingPlan()
    }
    // Auto-generate plan if coming from dashboard with startWizard flag
    else if (startWizard && !weeklyPlan && !isGuest && !hasAutoGenerated) {
      console.log('[MealPlanner] Auto-generating plan from dashboard navigation (startWizard)')
      setHasAutoGenerated(true)
      // Clear the state to prevent re-triggering
      window.history.replaceState({}, document.title)
      
      // Call generatePlan directly
      const autoGenerate = async () => {
        if (isGuest) {
          showToast('Please register to generate meal plans', 'error')
          return
        }

        try {
          setGenerating(true)
          const plan = await mealPlannerService.generateWeeklyPlan(excludedFoods)
          setWeeklyPlan(plan)
          showToast('Meal plan generated successfully!', 'success')
          setPreferencesOpen(false)
        } catch (error) {
          console.error('Error generating meal plan:', error)
          showToast(
            error.response?.data?.detail || 'Failed to generate meal plan. Please try again.',
            'error'
          )
        } finally {
          setGenerating(false)
        }
      }
      autoGenerate()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [location.state, weeklyPlan, isGuest, hasAutoGenerated]) // Run when location.state changes

  const generatePlan = async () => {
    if (isGuest) {
      showToast('Please register to generate meal plans', 'error')
      return
    }

    try {
      setGenerating(true)
      const plan = await mealPlannerService.generateWeeklyPlan(excludedFoods)
      setWeeklyPlan(plan)
      showToast('Meal plan generated successfully!', 'success')
      setPreferencesOpen(false)
    } catch (error) {
      console.error('Error generating meal plan:', error)
      showToast(
        error.response?.data?.detail || 'Failed to generate meal plan. Please try again.',
        'error'
      )
    } finally {
      setGenerating(false)
    }
  }

  const handleSwapClick = (day, mealType) => {
    setSelectedMeal({ day, mealType })
    setSwapModalOpen(true)
  }

  const handleSwapConfirm = (reason) => {
    console.log('Swap requested:', {
      meal: selectedMeal,
      reason: reason
    })
    setSwapModalOpen(false)
    setSelectedMeal(null)
    showToast('Swap request logged. Feature coming soon!', 'info')
  }

  const addExcludedFood = () => {
    const food = newFoodInput.trim()
    if (food && !excludedFoods.includes(food)) {
      setExcludedFoods([...excludedFoods, food])
      setNewFoodInput('')
    }
  }

  const removeExcludedFood = (food) => {
    setExcludedFoods(excludedFoods.filter(f => f !== food))
  }

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      addExcludedFood()
    }
  }

  const navigateDay = (direction) => {
    setActiveDayIndex((prev) => {
      if (direction === 'prev') {
        return prev === 0 ? DAYS.length - 1 : prev - 1
      } else {
        return prev === DAYS.length - 1 ? 0 : prev + 1
      }
    })
  }

  if (isGuest) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
        <Navbar />
        <div className="flex items-center justify-center min-h-[calc(100vh-80px)]">
          <div className="text-center">
            <Utensils className="mx-auto text-slate-400 mb-4" size={48} />
            <h2 className="text-xl font-semibold text-white mb-2">
              Register to Access Meal Planner
            </h2>
            <p className="text-slate-400 mb-6">
              Create an account to generate and manage your personalized meal plans.
            </p>
          </div>
        </div>
      </div>
    )
  }

  if (loading || generating) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
        <Navbar />
        <div className="flex items-center justify-center min-h-[calc(100vh-80px)]">
          <LoadingSpinner message={generating ? 'Generating your meal plan...' : 'Loading...'} />
        </div>
      </div>
    )
  }

  // Don't show welcome page if we're auto-generating or loading plan from dashboard
  const shouldAutoGenerate = location.state?.startWizard === true && !isGuest
  const shouldLoadPlan = location.state?.loadPlan === true && !isGuest
  
  if (!weeklyPlan && !shouldAutoGenerate && !shouldLoadPlan) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
        <Navbar />
        <div className="max-w-4xl mx-auto px-4 py-16">
          <div className="backdrop-blur-xl bg-slate-900/60 border border-white/10 rounded-3xl shadow-2xl shadow-purple-500/20 p-12 text-center">
            <Utensils className="mx-auto text-purple-400 mb-6" size={64} />
            <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent mb-4">
              Meal Planner
            </h1>
            <p className="text-slate-300 mb-8 text-lg">
              Generate your personalized weekly meal plan powered by AI
            </p>
            <button
              onClick={generatePlan}
              disabled={generating}
              className="bg-gradient-to-r from-purple-600 to-pink-600 text-white px-8 py-4 rounded-xl font-semibold text-lg hover:shadow-xl hover:shadow-purple-500/30 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 mx-auto"
            >
              {generating ? (
                <>
                  <Loader2 className="animate-spin" size={20} />
                  Generating...
                </>
              ) : (
                <>
                  <Utensils size={20} />
                  Generate Weekly Plan
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    )
  }

  const activeDay = weeklyPlan.days[activeDayIndex]

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      <Navbar />
      
      <div className="max-w-7xl mx-auto px-4 py-8">
        {/* Header with Preferences Button */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent mb-2">
              Meal Planner
            </h1>
            <p className="text-slate-400">Your personalized weekly meal plan</p>
          </div>
          <button
            onClick={() => setPreferencesOpen(true)}
            className="flex items-center gap-2 px-4 py-2 bg-slate-800/60 backdrop-blur-xl border border-white/10 rounded-xl text-white hover:bg-slate-800/80 transition-all duration-300"
          >
            <Settings size={20} />
            Preferences
          </button>
        </div>

        {/* Carousel Container */}
        <div className="relative h-[650px]">
          {/* Navigation Arrows */}
          <button
            onClick={() => navigateDay('prev')}
            className="absolute left-4 top-1/2 -translate-y-1/2 z-30 bg-slate-800/80 backdrop-blur-xl border border-white/10 rounded-full p-3 text-white hover:bg-slate-700/80 transition-all duration-300 hover:scale-110"
          >
            <ChevronLeft size={24} />
          </button>
          <button
            onClick={() => navigateDay('next')}
            className="absolute right-4 top-1/2 -translate-y-1/2 z-30 bg-slate-800/80 backdrop-blur-xl border border-white/10 rounded-full p-3 text-white hover:bg-slate-700/80 transition-all duration-300 hover:scale-110"
          >
            <ChevronRight size={24} />
          </button>

          {/* Cards Container */}
          <div className="relative w-full h-full flex items-center justify-center overflow-hidden">
            {weeklyPlan.days.map((day, index) => {
              const isActive = index === activeDayIndex
              const offset = index - activeDayIndex
              
              return (
                <motion.div
                  key={day.day}
                  initial={false}
                  animate={{
                    opacity: isActive ? 1 : 0.4,
                    scale: isActive ? 1.1 : 0.85,
                    x: offset * 380,
                    zIndex: isActive ? 10 : Math.max(1, 10 - Math.abs(offset))
                  }}
                  transition={{ duration: 0.4, ease: "easeInOut" }}
                  className={`absolute ${
                    isActive ? 'cursor-default' : 'cursor-pointer'
                  }`}
                  onClick={() => !isActive && setActiveDayIndex(index)}
                >
                    {/* Card */}
                    <div
                      className={`backdrop-blur-xl border rounded-3xl p-6 shadow-2xl transition-all duration-300 ${
                        isActive
                          ? 'bg-slate-900/80 border-purple-500/50 shadow-purple-500/30 w-[500px]'
                          : 'bg-slate-900/40 border-white/10 w-[400px]'
                      }`}
                    >
                      {/* Day Header */}
                      <div className="text-center mb-6">
                        <h2 className={`font-bold mb-1 ${
                          isActive ? 'text-2xl text-purple-300' : 'text-xl text-slate-400'
                        }`}>
                          {day.day}
                        </h2>
                        <p className="text-sm text-slate-500">
                          {day.total_calories} calories
                        </p>
                      </div>

                      {/* Meals */}
                      <div className="space-y-3">
                        {MEAL_TYPES.map(({ key, label, icon: Icon }) => {
                          const meal = day[key]
                          if (!meal) return null

                          return (
                            <motion.div
                              key={key}
                              className="group relative bg-slate-800/40 rounded-xl p-4 border border-white/5 hover:border-purple-500/30 transition-all duration-300"
                              whileHover={{ scale: 1.02 }}
                            >
                              <div className="flex items-center gap-3">
                                <div className="flex-shrink-0">
                                  <Icon 
                                    size={24} 
                                    className={isActive ? 'text-purple-400' : 'text-slate-500'} 
                                  />
                                </div>
                                <div className="flex-1 min-w-0">
                                  <h3 className={`font-semibold truncate ${
                                    isActive ? 'text-white' : 'text-slate-300'
                                  }`}>
                                    {meal.name}
                                  </h3>
                                  <p className="text-sm text-slate-500">
                                    {meal.calories} cal
                                  </p>
                                </div>
                                {isActive && (
                                  <motion.button
                                    initial={{ opacity: 0 }}
                                    whileHover={{ opacity: 1 }}
                                    className="opacity-0 group-hover:opacity-100 flex-shrink-0 p-2 rounded-lg bg-purple-600/20 hover:bg-purple-600/40 transition-all duration-200"
                                    onClick={(e) => {
                                      e.stopPropagation()
                                      handleSwapClick(day.day, key)
                                    }}
                                  >
                                    <RotateCcw size={18} className="text-purple-300" />
                                  </motion.button>
                                )}
                              </div>
                            </motion.div>
                          )
                        })}
                      </div>
                    </div>
                  </motion.div>
                )
              })}
          </div>
        </div>

        {/* Day Indicators */}
        <div className="flex justify-center gap-2 mt-8">
          {DAYS.map((day, index) => (
            <button
              key={day}
              onClick={() => setActiveDayIndex(index)}
              className={`w-3 h-3 rounded-full transition-all duration-300 ${
                index === activeDayIndex
                  ? 'bg-purple-500 w-8'
                  : 'bg-slate-600 hover:bg-slate-500'
              }`}
            />
          ))}
        </div>
      </div>

      {/* Preferences Drawer */}
      <AnimatePresence>
        {preferencesOpen && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 bg-black/50 backdrop-blur-sm z-40"
              onClick={() => setPreferencesOpen(false)}
            />
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className="fixed right-0 top-0 h-full w-full max-w-md bg-slate-900/95 backdrop-blur-xl border-l border-white/10 shadow-2xl z-50 overflow-y-auto"
            >
              <div className="p-6">
                <div className="flex items-center justify-between mb-6">
                  <h2 className="text-2xl font-bold text-white">Preferences</h2>
                  <button
                    onClick={() => setPreferencesOpen(false)}
                    className="p-2 rounded-lg hover:bg-slate-800 transition-colors"
                  >
                    <X size={24} className="text-slate-400" />
                  </button>
                </div>

                <div className="mb-6">
                  <label className="block text-sm font-semibold text-slate-300 mb-3">
                    Foods to Exclude
                  </label>
                  <div className="flex gap-2 mb-3">
                    <input
                      type="text"
                      value={newFoodInput}
                      onChange={(e) => setNewFoodInput(e.target.value)}
                      onKeyPress={handleKeyPress}
                      placeholder="Add food to exclude..."
                      className="flex-1 px-4 py-2 bg-slate-800/60 border border-white/10 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:border-purple-500/50"
                    />
                    <button
                      onClick={addExcludedFood}
                      className="px-4 py-2 bg-purple-600 hover:bg-purple-700 rounded-xl text-white transition-colors"
                    >
                      <Plus size={20} />
                    </button>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {excludedFoods.map((food) => (
                      <span
                        key={food}
                        className="inline-flex items-center gap-2 px-3 py-1.5 bg-slate-800/60 border border-white/10 rounded-lg text-sm text-slate-300"
                      >
                        {food}
                        <button
                          onClick={() => removeExcludedFood(food)}
                          className="hover:text-red-400 transition-colors"
                        >
                          <X size={14} />
                        </button>
                      </span>
                    ))}
                  </div>
                </div>

                <button
                  onClick={generatePlan}
                  disabled={generating}
                  className="w-full py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-xl font-semibold hover:shadow-xl hover:shadow-purple-500/30 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                >
                  {generating ? (
                    <>
                      <Loader2 className="animate-spin" size={20} />
                      Regenerating Plan...
                    </>
                  ) : (
                    <>
                      <RotateCcw size={20} />
                      Regenerate Plan
                    </>
                  )}
                </button>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Swap Modal */}
      <AnimatePresence>
        {swapModalOpen && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50"
              onClick={() => setSwapModalOpen(false)}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              className="fixed inset-0 flex items-center justify-center z-50 p-4"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="backdrop-blur-xl bg-slate-900/95 border border-white/10 rounded-3xl shadow-2xl p-8 max-w-md w-full">
                <div className="flex items-center justify-between mb-6">
                  <h2 className="text-2xl font-bold text-white">Swap Meal</h2>
                  <button
                    onClick={() => setSwapModalOpen(false)}
                    className="p-2 rounded-lg hover:bg-slate-800 transition-colors"
                  >
                    <X size={24} className="text-slate-400" />
                  </button>
                </div>
                <p className="text-slate-300 mb-6">
                  Why do you want to swap this meal?
                </p>
                <div className="space-y-3">
                  {SWAP_REASONS.map((reason) => (
                    <button
                      key={reason}
                      onClick={() => handleSwapConfirm(reason)}
                      className="w-full text-left px-4 py-3 bg-slate-800/60 border border-white/10 rounded-xl text-white hover:bg-slate-800/80 hover:border-purple-500/50 transition-all duration-300"
                    >
                      {reason}
                    </button>
                  ))}
                </div>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  )
}

export default MealPlanner

